### ISSUE TITLE
文件找不到

### ISSUE THREAD

**Issue by zzczdr** [zhanzecheng/SOHU_competition#2]
您好，非常感谢您分享您的代码。但是，根据您给出的代码，其中几个文件没有找到，
![image](https://user-images.githubusercontent.com/38033013/52688844-0c9fad80-2f93-11e9-8953-1b4630b1ebf0.png)
打扰您了，感谢您能够给出指导！！！

**Comment by zzczdr** [comment]
![image](https://user-images.githubusercontent.com/38033013/52688918-55576680-2f93-11e9-9ca7-f91517230f92.png)
这个文件也没有！

**Comment by zhanzecheng** [comment]
hi, 第一点你看一下train_tfidf.py 这个文件。OCR的特征在决赛阶段由于时间限制我们没有使用，你可以把它去掉

**Comment by Littleffsmile** [comment]
您好，如果没有OCR特征产生的文件，那后面的stacking需要数据，是如何运行的呢?感谢您能做出指导。

**Comment by zhanzecheng** [comment]
> 您好，如果没有OCR特征产生的文件，那后面的stacking需要数据，是如何运行的呢?感谢您能做出指导。

Hi Littleffsmile,  我们最终决赛的代码是没有使用OCR特征的，但是在初赛的时候证明是有效的，因此在stacking中加进去了。如果你要使用，可以修改./ocr/demo.py文件来提取，如果不使用，可以修改stacking中的相应代码，去掉ocr特征。

**Comment by zzczdr** [comment]
您文件下的./ocr/demo.py中会出现import错误
![image](https://user-images.githubusercontent.com/38033013/52837900-a7cb8b00-312b-11e9-9359-b10be07f7846.png)我看了下是需要运行 .c文件，我用的是spyder运行的，您是怎么解决这个问题的？多谢多谢

**Comment by zhanzecheng** [comment]
@zzczdr Hi, 你先要处理安装好OCR代码相应环境
https://github.com/zhanzecheng/SOHU_competition/blob/master/src/ocr/setup.sh
