### ISSUE TITLE
请问比赛的数据集能分享一下吗？找不到下载的地址，想重现一下，谢谢

### ISSUE THREAD

**Issue by QQ2737499951** [zhanzecheng/SOHU_competition#4]
请问比赛的数据集能分享一下吗？找不到下载的地址，想重现一下，谢谢

**Comment by zhanzecheng** [comment]
Hi 应该是biendata官方没有继续放出来了，抱歉我这边也没有保存当时的数据集，sorry

**Comment by QQ2737499951** [comment]
> Hi 应该是biendata官方没有继续放出来了，抱歉我这边也没有保存当时的数据集，sorry


名称 | 格式 | 链接 | 提取码
-- | -- | -- | --
搜狐第二届算法大赛数据 | folder (132.0 GB) | https://pan.baidu.com/s/1f0TKzqKGB-EQwmvoKHRFAg | 

官网的这个数据集的链接失效了。您看看您的百度云盘中有没有保存？能否分享一下，谢谢
